name: 12 - Working with Outputs

on:
  workflow_dispatch:
    inputs:
      build_status:
        type: choice
        options:
          - success
          - failure
        default: success

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ steps.build.outputs.status }}

    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "GITHUB_OUTPUT path is $GITHUB_OUTPUT"

      - name: Build
        id: build
        # We use github.event.inputs to ensure the value is correctly resolved
        run: echo "status=${{ github.event.inputs.build_status }}" >> "$GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # In an 'if' conditional, you don't need the ${{ }} wrappers
    if: needs.build.outputs.build_status == 'success'
    steps:
      - name: Deploy
        run: echo "Deploying"
