name: gitleaks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # REQUIRED

      - name: Run Gitleaks (full scan)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
